// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: basic.proto

package basicv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	sharedv1 "github.com/go-sphere/protoc-gen-sphere/generate/http/testdata/gen/sharedv1"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = (*context.Context)(nil)
var _ = (*httpx.Router)(nil)
var _ = (*httpz.ErrorResponse)(nil)
var _ = (*sharedv1.TestEnum)(nil)

const OperationBasicServiceBodyPathTest = "/testdata.basic.v1.BasicService/BodyPathTest"
const OperationBasicServiceRunTest = "/testdata.basic.v1.BasicService/RunTest"

var EndpointsBasicService = [...][3]string{
	{OperationBasicServiceRunTest, "POST", "/api/test/:path_test1/second/:path_test2"},
	{OperationBasicServiceBodyPathTest, "POST", "/api/test/body_path_test"},
}

type BasicServiceHTTPServer interface {
	// BodyPathTest test comment line1
	// test comment line2
	// test comment line3
	BodyPathTest(context.Context, *BodyPathTestRequest) (*BodyPathTestResponse, error)
	RunTest(context.Context, *RunTestRequest) (*RunTestResponse, error)
}

// @Summary RunTest
// @Tags testdata.basic.v1,testdata.basic.v1.BasicService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param path_test1 path string true "path_test1"
// @Param path_test2 path integer true "path_test2"
// @Param query_test1 query string false "query_test1"
// @Param query_test2 query integer false "query_test2"
// @Param enum_test1 query []sharedv1.TestEnum false "enum_test1"
// @Param request body RunTestRequest true "request body"
// @Success 200 {object} httpz.DataResponse[RunTestResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/test/{path_test1}/second/{path_test2} [post]
func _BasicService_RunTest0_HTTP_Handler(srv BasicServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*RunTestResponse, error) {
		var in RunTestRequest
		if err := ctx.BindJSON(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.RunTest(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary BodyPathTest
// @Description test comment line1, test comment line2, test comment line3
// @Tags testdata.basic.v1,testdata.basic.v1.BasicService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request body BodyPathTestRequest_Request true "request body"
// @Success 200 {object} httpz.DataResponse[[]BodyPathTestResponse_Response]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/test/body_path_test [post]
func _BasicService_BodyPathTest0_HTTP_Handler(srv BasicServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) ([]*BodyPathTestResponse_Response, error) {
		var in BodyPathTestRequest
		if err := ctx.BindJSON(&in.Request); err != nil {
			return nil, err
		}
		out, err := srv.BodyPathTest(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out.Response, nil
	})
}

func RegisterBasicServiceHTTPServer(route httpx.Router, srv BasicServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("POST", "/api/test/:path_test1/second/:path_test2", _BasicService_RunTest0_HTTP_Handler(srv))
	r.Handle("POST", "/api/test/body_path_test", _BasicService_BodyPathTest0_HTTP_Handler(srv))
}
