// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: binding.proto

package bindingv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = (*context.Context)(nil)
var _ = (*httpx.Router)(nil)
var _ = (*httpz.ErrorResponse)(nil)

const OperationBindingServiceMix = "/testdata.binding.v1.BindingService/Mix"

var EndpointsBindingService = [...][3]string{
	{OperationBindingServiceMix, "POST", "/api/mix/:path_id"},
}

type BindingServiceHTTPServer interface {
	// Mix Mix exercises uri, header and default-location query bindings together.
	Mix(context.Context, *MixRequest) (*MixResponse, error)
}

// @Summary Mix
// @Description Mix exercises uri, header and default-location query bindings together.
// @Tags testdata.binding.v1,testdata.binding.v1.BindingService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param header_token header string false "header_token"
// @Param path_id path string true "path_id"
// @Param q1 query string false "q1"
// @Param q2 query integer false "q2"
// @Param request body MixRequest true "request body"
// @Success 200 {object} httpz.DataResponse[MixResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/mix/{path_id} [post]
func _BindingService_Mix0_HTTP_Handler(srv BindingServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*MixResponse, error) {
		var in MixRequest
		if err := ctx.BindJSON(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindHeader(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.Mix(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterBindingServiceHTTPServer(route httpx.Router, srv BindingServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("POST", "/api/mix/:path_id", _BindingService_Mix0_HTTP_Handler(srv))
}
