// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: complex.proto

package complexv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = (*context.Context)(nil)
var _ = (*httpx.Router)(nil)
var _ = (*httpz.ErrorResponse)(nil)

const OperationComplexServiceGetItem = "/testdata.complex.v1.ComplexService/GetItem"
const OperationComplexServiceUpdateItem = "/testdata.complex.v1.ComplexService/UpdateItem"

var EndpointsComplexService = [...][3]string{
	{OperationComplexServiceGetItem, "GET", "/api/v2/items/:id"},
	{OperationComplexServiceGetItem, "GET", "/api/items/:id"},
	{OperationComplexServiceUpdateItem, "PUT", "/api/items/:id"},
}

type ComplexServiceHTTPServer interface {
	// GetItem GetItem fetches an item by id.
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
	UpdateItem(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error)
}

// @Summary GetItem
// @Description GetItem fetches an item by id.
// @Tags testdata.complex.v1,testdata.complex.v1.ComplexService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id path string true "id"
// @Success 200 {object} httpz.DataResponse[GetItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/v2/items/{id} [get]
func _ComplexService_GetItem0_HTTP_Handler(srv ComplexServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*GetItemResponse, error) {
		var in GetItemRequest
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.GetItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary GetItem
// @Description GetItem fetches an item by id.
// @Tags testdata.complex.v1,testdata.complex.v1.ComplexService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id path string true "id"
// @Success 200 {object} httpz.DataResponse[GetItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/items/{id} [get]
func _ComplexService_GetItem1_HTTP_Handler(srv ComplexServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*GetItemResponse, error) {
		var in GetItemRequest
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.GetItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary UpdateItem
// @Tags testdata.complex.v1,testdata.complex.v1.ComplexService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id path string true "id"
// @Param request body Item true "request body"
// @Success 200 {object} httpz.DataResponse[Item]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/items/{id} [put]
func _ComplexService_UpdateItem0_HTTP_Handler(srv ComplexServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*Item, error) {
		var in UpdateItemRequest
		if err := ctx.BindJSON(&in.Item); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.UpdateItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out.Item, nil
	})
}

func RegisterComplexServiceHTTPServer(route httpx.Router, srv ComplexServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("GET", "/api/v2/items/:id", _ComplexService_GetItem0_HTTP_Handler(srv))
	r.Handle("GET", "/api/items/:id", _ComplexService_GetItem1_HTTP_Handler(srv))
	r.Handle("PUT", "/api/items/:id", _ComplexService_UpdateItem0_HTTP_Handler(srv))
}
