// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: custom_verb.proto

package verbv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = new(context.Context)
var _ = new(httpx.Router)
var _ = new(httpz.ErrorResponse)

const OperationVerbServiceGenerateReport = "/testdata.verb.v1.VerbService/GenerateReport"

var EndpointsVerbService = [...][3]string{
	{OperationVerbServiceGenerateReport, "POST", "/v1/reports:generate"},
}

type VerbServiceHTTPServer interface {
	GenerateReport(context.Context, *GenerateReportRequest) (*GenerateReportResponse, error)
}

// @Summary GenerateReport
// @Tags testdata.verb.v1,testdata.verb.v1.VerbService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param name query string false "name"
// @Param request body GenerateReportRequest true "request body"
// @Success 200 {object} httpz.DataResponse[GenerateReportResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /v1/reports:generate [post]
func _VerbService_GenerateReport0_HTTP_Handler(srv VerbServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*GenerateReportResponse, error) {
		var in GenerateReportRequest
		if err := ctx.BindJSON(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		out, err := srv.GenerateReport(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterVerbServiceHTTPServer(route httpx.Router, srv VerbServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("POST", "/v1/reports:generate", _VerbService_GenerateReport0_HTTP_Handler(srv))
}
