// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: no_http.proto

package nohttpv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = (*context.Context)(nil)
var _ = (*httpx.Router)(nil)
var _ = (*httpz.ErrorResponse)(nil)

const OperationNoHTTPServicePing = "/testdata.nohttp.v1.NoHTTPService/Ping"

var EndpointsNoHTTPService = [...][3]string{
	{OperationNoHTTPServicePing, "POST", "/testdata.nohttp.v1.NoHTTPService/Ping"},
}

type NoHTTPServiceHTTPServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// @Summary Ping
// @Tags testdata.nohttp.v1,testdata.nohttp.v1.NoHTTPService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request body PingRequest true "request body"
// @Success 200 {object} httpz.DataResponse[PingResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /testdata.nohttp.v1.NoHTTPService/Ping [post]
func _NoHTTPService_Ping0_HTTP_Handler(srv NoHTTPServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*PingResponse, error) {
		var in PingRequest
		if err := ctx.BindJSON(&in); err != nil {
			return nil, err
		}
		out, err := srv.Ping(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterNoHTTPServiceHTTPServer(route httpx.Router, srv NoHTTPServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("POST", "/testdata.nohttp.v1.NoHTTPService/Ping", _NoHTTPService_Ping0_HTTP_Handler(srv))
}
