// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: integration.proto

package integrationv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = (*context.Context)(nil)
var _ = (*httpx.Router)(nil)
var _ = (*httpz.ErrorResponse)(nil)

const OperationIntegrationServiceCreateItem = "/testdata.integration.v1.IntegrationService/CreateItem"
const OperationIntegrationServiceListItems = "/testdata.integration.v1.IntegrationService/ListItems"
const OperationIntegrationServiceUploadItem = "/testdata.integration.v1.IntegrationService/UploadItem"

var EndpointsIntegrationService = [...][3]string{
	{OperationIntegrationServiceCreateItem, "POST", "/api/tenants/:tenant_id/items"},
	{OperationIntegrationServiceUploadItem, "POST", "/api/tenants/:tenant_id/items/upload"},
	{OperationIntegrationServiceListItems, "GET", "/api/tenants/:tenant_id/items"},
}

type IntegrationServiceHTTPServer interface {
	// CreateItem CreateItem carries the whole request as JSON while pulling tenant_id from
	// the path, request_id from a header and not_before from the query string.
	CreateItem(context.Context, *CreateItemRequest) (*ItemResponse, error)
	// ListItems ListItems exercises well-known types (Timestamp/Duration/wrappers) bound as
	// query parameters, which must render as scalar Swagger types.
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
	// UploadItem UploadItem decodes its payload from multipart form data (no JSON body).
	UploadItem(context.Context, *UploadItemRequest) (*ItemResponse, error)
}

// @Summary CreateItem
// @Description CreateItem carries the whole request as JSON while pulling tenant_id from, the path, request_id from a header and not_before from the query string.
// @Tags testdata.integration.v1,testdata.integration.v1.IntegrationService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request_id header string false "request_id"
// @Param tenant_id path string true "tenant_id"
// @Param not_before query string false "not_before"
// @Param request body CreateItemRequest true "request body"
// @Success 200 {object} httpz.DataResponse[ItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/tenants/{tenant_id}/items [post]
func _IntegrationService_CreateItem0_HTTP_Handler(srv IntegrationServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*ItemResponse, error) {
		var in CreateItemRequest
		if err := ctx.BindJSON(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindHeader(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.CreateItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary UploadItem
// @Description UploadItem decodes its payload from multipart form data (no JSON body).
// @Tags testdata.integration.v1,testdata.integration.v1.IntegrationService
// @Accept mpfd
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param tenant_id path string true "tenant_id"
// @Param filename formData string false "filename"
// @Param size formData integer false "size"
// @Success 200 {object} httpz.DataResponse[ItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/tenants/{tenant_id}/items/upload [post]
func _IntegrationService_UploadItem0_HTTP_Handler(srv IntegrationServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*ItemResponse, error) {
		var in UploadItemRequest
		if err := ctx.BindForm(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.UploadItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary ListItems
// @Description ListItems exercises well-known types (Timestamp/Duration/wrappers) bound as, query parameters, which must render as scalar Swagger types.
// @Tags testdata.integration.v1,testdata.integration.v1.IntegrationService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param tenant_id path string true "tenant_id"
// @Param created_after query string false "created_after"
// @Param max_age query string false "max_age"
// @Param keyword query string false "keyword"
// @Param limit query integer false "limit"
// @Param active query boolean false "active"
// @Success 200 {object} httpz.DataResponse[ListItemsResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/tenants/{tenant_id}/items [get]
func _IntegrationService_ListItems0_HTTP_Handler(srv IntegrationServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*ListItemsResponse, error) {
		var in ListItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.ListItems(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterIntegrationServiceHTTPServer(route httpx.Router, srv IntegrationServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("POST", "/api/tenants/:tenant_id/items", _IntegrationService_CreateItem0_HTTP_Handler(srv))
	r.Handle("POST", "/api/tenants/:tenant_id/items/upload", _IntegrationService_UploadItem0_HTTP_Handler(srv))
	r.Handle("GET", "/api/tenants/:tenant_id/items", _IntegrationService_ListItems0_HTTP_Handler(srv))
}
