// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc-gen-sphere v0.0.0-golden
// - protoc            v5.29.0
// source: integration.proto

package integrationv1

import (
	context "context"
	errors "errors"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
	io "io"
)

var _ = new(context.Context)
var _ = new(httpx.Router)
var _ = new(httpz.ErrorResponse)

const OperationIntegrationServiceCreateItem = "/testdata.integration.v1.IntegrationService/CreateItem"
const OperationIntegrationServiceUploadItem = "/testdata.integration.v1.IntegrationService/UploadItem"
const OperationIntegrationServiceListItems = "/testdata.integration.v1.IntegrationService/ListItems"

var EndpointsIntegrationService = [...][3]string{
	{OperationIntegrationServiceCreateItem, "POST", "/api/tenants/:tenant_id/items"},
	{OperationIntegrationServiceUploadItem, "POST", "/api/tenants/:tenant_id/items/upload"},
	{OperationIntegrationServiceListItems, "GET", "/api/tenants/:tenant_id/items"},
}

type IntegrationServiceHTTPServer interface {
	// CreateItem CreateItem carries the whole request as JSON while pulling tenant_id from
	// the path and request_id from a header.
	CreateItem(context.Context, *CreateItemRequest) (*ItemResponse, error)
	// UploadItem UploadItem decodes its payload from multipart form data (no JSON body).
	UploadItem(context.Context, *UploadItemRequest) (*ItemResponse, error)
	// ListItems ListItems binds plain and proto3 optional scalars as query parameters.
	ListItems(context.Context, *ListItemsRequest) (*ListItemsResponse, error)
}

// @Summary CreateItem
// @Description CreateItem carries the whole request as JSON while pulling tenant_id from, the path and request_id from a header.
// @Tags testdata.integration.v1,testdata.integration.v1.IntegrationService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request_id header string false "request_id"
// @Param tenant_id path string true "tenant_id"
// @Param request body CreateItemRequest true "request body"
// @Success 200 {object} httpz.DataResponse[ItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/tenants/{tenant_id}/items [post]
func _IntegrationService_CreateItem0_HTTP_Handler(srv IntegrationServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*ItemResponse, error) {
		var in CreateItemRequest
		if err := ctx.BindJSON(&in); err != nil && !errors.Is(err, io.EOF) {
			return nil, err
		}
		if err := ctx.BindHeader(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.CreateItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary UploadItem
// @Description UploadItem decodes its payload from multipart form data (no JSON body).
// @Tags testdata.integration.v1,testdata.integration.v1.IntegrationService
// @Accept mpfd
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param tenant_id path string true "tenant_id"
// @Param filename formData string false "filename"
// @Param size formData integer false "size"
// @Success 200 {object} httpz.DataResponse[ItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/tenants/{tenant_id}/items/upload [post]
func _IntegrationService_UploadItem0_HTTP_Handler(srv IntegrationServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*ItemResponse, error) {
		var in UploadItemRequest
		if err := ctx.BindForm(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.UploadItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary ListItems
// @Description ListItems binds plain and proto3 optional scalars as query parameters.
// @Tags testdata.integration.v1,testdata.integration.v1.IntegrationService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param tenant_id path string true "tenant_id"
// @Param created_after_unix query integer false "created_after_unix"
// @Param max_age_seconds query integer false "max_age_seconds"
// @Param keyword query string false "keyword"
// @Param limit query integer false "limit"
// @Param active query boolean false "active"
// @Success 200 {object} httpz.DataResponse[ListItemsResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/tenants/{tenant_id}/items [get]
func _IntegrationService_ListItems0_HTTP_Handler(srv IntegrationServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*ListItemsResponse, error) {
		var in ListItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.ListItems(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterIntegrationServiceHTTPServer(route httpx.Router, srv IntegrationServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("POST", "/api/tenants/:tenant_id/items", _IntegrationService_CreateItem0_HTTP_Handler(srv))
	r.Handle("POST", "/api/tenants/:tenant_id/items/upload", _IntegrationService_UploadItem0_HTTP_Handler(srv))
	r.Handle("GET", "/api/tenants/:tenant_id/items", _IntegrationService_ListItems0_HTTP_Handler(srv))
}
