// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: no_body.proto

package nobodyv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = (*context.Context)(nil)
var _ = (*httpx.Router)(nil)
var _ = (*httpz.ErrorResponse)(nil)

const OperationNoBodyServiceDeleteItem = "/testdata.nobody.v1.NoBodyService/DeleteItem"
const OperationNoBodyServiceGetItem = "/testdata.nobody.v1.NoBodyService/GetItem"

var EndpointsNoBodyService = [...][3]string{
	{OperationNoBodyServiceGetItem, "GET", "/api/items/:id"},
	{OperationNoBodyServiceDeleteItem, "DELETE", "/api/items/:id"},
}

type NoBodyServiceHTTPServer interface {
	// DeleteItem DeleteItem declares `body: "*"` on a DELETE. The body must be ignored too;
	// its fields are bound from the URI/query instead.
	DeleteItem(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
	// GetItem GetItem declares `body: "*"` on a GET, which is invalid. The generator must
	// drop the body and bind only the URI/query params.
	GetItem(context.Context, *GetItemRequest) (*GetItemResponse, error)
}

// @Summary GetItem
// @Description GetItem declares `body: "*"` on a GET, which is invalid. The generator must, drop the body and bind only the URI/query params.
// @Tags testdata.nobody.v1,testdata.nobody.v1.NoBodyService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param auth_token header string false "auth_token"
// @Param id path integer true "id"
// @Param filter query string false "filter"
// @Success 200 {object} httpz.DataResponse[GetItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/items/{id} [get]
func _NoBodyService_GetItem0_HTTP_Handler(srv NoBodyServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*GetItemResponse, error) {
		var in GetItemRequest
		if err := ctx.BindHeader(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.GetItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary DeleteItem
// @Description DeleteItem declares `body: "*"` on a DELETE. The body must be ignored too;, its fields are bound from the URI/query instead.
// @Tags testdata.nobody.v1,testdata.nobody.v1.NoBodyService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id path integer true "id"
// @Param reason query string false "reason"
// @Success 200 {object} httpz.DataResponse[DeleteItemResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/items/{id} [delete]
func _NoBodyService_DeleteItem0_HTTP_Handler(srv NoBodyServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*DeleteItemResponse, error) {
		var in DeleteItemRequest
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.DeleteItem(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterNoBodyServiceHTTPServer(route httpx.Router, srv NoBodyServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("GET", "/api/items/:id", _NoBodyService_GetItem0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/items/:id", _NoBodyService_DeleteItem0_HTTP_Handler(srv))
}
