// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: streaming.proto

package streamingv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = new(context.Context)
var _ = new(httpx.Router)
var _ = new(httpz.ErrorResponse)

const OperationStreamServiceChat = "/testdata.streaming.v1.StreamService/Chat"
const OperationStreamServiceStatus = "/testdata.streaming.v1.StreamService/Status"
const OperationStreamServiceWatch = "/testdata.streaming.v1.StreamService/Watch"

var EndpointsStreamService = [...][3]string{
	{OperationStreamServiceWatch, "GET", "/api/stream/watch/:topic"},
	{OperationStreamServiceChat, "POST", "/api/stream/chat"},
	{OperationStreamServiceStatus, "GET", "/api/stream/status"},
}

type StreamServiceHTTPServer interface {
	// Chat Server-streaming over POST with a JSON body (LLM-completion shape).
	Chat(context.Context, *ChatRequest, func(*ChatResponse) error) error
	// Status Unary method in the same service: both shapes must coexist.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Watch Server-streaming over GET: query-bound request, SSE response, and a
	// Last-Event-ID header for business-side resume.
	Watch(context.Context, *WatchRequest, func(*WatchResponse) error) error
}

// @Summary Watch
// @Description Server-streaming over GET: query-bound request, SSE response, and a, Last-Event-ID header for business-side resume.
// @Tags testdata.streaming.v1,testdata.streaming.v1.StreamService
// @Accept json
// @Produce text/event-stream
// @Param Authorization header string false "Bearer token"
// @Param last_event_id header string false "last_event_id"
// @Param topic path string true "topic"
// @Param limit query integer false "limit"
// @Success 200 {object} WatchResponse "server-sent events stream of this message; terminated by a done or error event"
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/stream/watch/{topic} [get]
func _StreamService_Watch0_HTTP_Handler(srv StreamServiceHTTPServer) httpx.Handler {
	return httpz.WithSSE(func(ctx httpx.Context) (httpz.SSEStream[*WatchResponse], error) {
		var in WatchRequest
		if err := ctx.BindHeader(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		stdCtx := ctx.Context()
		return func(send func(*WatchResponse) error) error {
			return srv.Watch(stdCtx, &in, send)
		}, nil
	})
}

// @Summary Chat
// @Description Server-streaming over POST with a JSON body (LLM-completion shape).
// @Tags testdata.streaming.v1,testdata.streaming.v1.StreamService
// @Accept json
// @Produce text/event-stream
// @Param Authorization header string false "Bearer token"
// @Param request body ChatRequest true "request body"
// @Success 200 {object} ChatResponse "server-sent events stream of this message; terminated by a done or error event"
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/stream/chat [post]
func _StreamService_Chat0_HTTP_Handler(srv StreamServiceHTTPServer) httpx.Handler {
	return httpz.WithSSE(func(ctx httpx.Context) (httpz.SSEStream[*ChatResponse], error) {
		var in ChatRequest
		if err := ctx.BindJSON(&in); err != nil {
			return nil, err
		}
		stdCtx := ctx.Context()
		return func(send func(*ChatResponse) error) error {
			return srv.Chat(stdCtx, &in, send)
		}, nil
	})
}

// @Summary Status
// @Description Unary method in the same service: both shapes must coexist.
// @Tags testdata.streaming.v1,testdata.streaming.v1.StreamService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param id query string false "id"
// @Success 200 {object} httpz.DataResponse[StatusResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/stream/status [get]
func _StreamService_Status0_HTTP_Handler(srv StreamServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*StatusResponse, error) {
		var in StatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		out, err := srv.Status(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterStreamServiceHTTPServer(route httpx.Router, srv StreamServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("GET", "/api/stream/watch/:topic", _StreamService_Watch0_HTTP_Handler(srv))
	r.Handle("POST", "/api/stream/chat", _StreamService_Chat0_HTTP_Handler(srv))
	r.Handle("GET", "/api/stream/status", _StreamService_Status0_HTTP_Handler(srv))
}
