// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: swag_edge.proto

package swagv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = new(context.Context)
var _ = new(httpx.Router)
var _ = new(httpz.ErrorResponse)

const OperationSwagEdgeServiceEnumListQuery = "/testdata.swag.v1.SwagEdgeService/EnumListQuery"
const OperationSwagEdgeServiceEnumQuery = "/testdata.swag.v1.SwagEdgeService/EnumQuery"
const OperationSwagEdgeServiceGetWithForm = "/testdata.swag.v1.SwagEdgeService/GetWithForm"
const OperationSwagEdgeServiceListResponseBody = "/testdata.swag.v1.SwagEdgeService/ListResponseBody"
const OperationSwagEdgeServiceMapBody = "/testdata.swag.v1.SwagEdgeService/MapBody"
const OperationSwagEdgeServiceMapResponseBody = "/testdata.swag.v1.SwagEdgeService/MapResponseBody"
const OperationSwagEdgeServiceNoBodyPost = "/testdata.swag.v1.SwagEdgeService/NoBodyPost"
const OperationSwagEdgeServiceScalarResponseBody = "/testdata.swag.v1.SwagEdgeService/ScalarResponseBody"
const OperationSwagEdgeServiceWildcardList = "/testdata.swag.v1.SwagEdgeService/WildcardList"

var EndpointsSwagEdgeService = [...][3]string{
	{OperationSwagEdgeServiceNoBodyPost, "POST", "/api/swag/post"},
	{OperationSwagEdgeServiceGetWithForm, "GET", "/api/swag/form"},
	{OperationSwagEdgeServiceWildcardList, "GET", "/api/swag/repeated/*names"},
	{OperationSwagEdgeServiceMapBody, "POST", "/api/swag/map"},
	{OperationSwagEdgeServiceScalarResponseBody, "GET", "/api/swag/scalar-response"},
	{OperationSwagEdgeServiceMapResponseBody, "GET", "/api/swag/map-response"},
	{OperationSwagEdgeServiceListResponseBody, "GET", "/api/swag/list-response"},
	{OperationSwagEdgeServiceEnumQuery, "GET", "/api/swag/enum"},
	{OperationSwagEdgeServiceEnumListQuery, "GET", "/api/swag/enum-list"},
}

type SwagEdgeServiceHTTPServer interface {
	// EnumListQuery EnumListQuery binds a repeated enum as a query parameter. swag only
	// accepts primitive arrays in parameters, so the elements must render as
	// their underlying scalar.
	EnumListQuery(context.Context, *EnumListQueryRequest) (*EnumQueryResponse, error)
	// EnumQuery EnumQuery binds an enum field as a query parameter.
	EnumQuery(context.Context, *EnumQueryRequest) (*EnumQueryResponse, error)
	// GetWithForm GetWithForm binds fields as form data on a GET request.
	GetWithForm(context.Context, *GetWithFormRequest) (*GetWithFormResponse, error)
	// ListResponseBody ListResponseBody projects the response onto a repeated message field.
	ListResponseBody(context.Context, *ListResponseBodyRequest) (*ListResponseBodyResponse, error)
	// MapBody MapBody projects the request body onto a map field.
	MapBody(context.Context, *MapBodyRequest) (*MapBodyResponse, error)
	// MapResponseBody MapResponseBody projects the response onto a map field.
	MapResponseBody(context.Context, *MapResponseBodyRequest) (*MapResponseBodyResponse, error)
	// NoBodyPost NoBodyPost declares a POST without a body: the handler never binds JSON,
	// so the Swagger block must not advertise a request body.
	NoBodyPost(context.Context, *NoBodyPostRequest) (*NoBodyPostResponse, error)
	// ScalarResponseBody ScalarResponseBody projects the response onto a scalar string field.
	ScalarResponseBody(context.Context, *ScalarResponseBodyRequest) (*ScalarResponseBodyResponse, error)
	// WildcardList WildcardList binds a repeated string to a catch-all path segment.
	WildcardList(context.Context, *WildcardListRequest) (*WildcardListResponse, error)
}

// @Summary NoBodyPost
// @Description NoBodyPost declares a POST without a body: the handler never binds JSON,, so the Swagger block must not advertise a request body.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param name query string false "name"
// @Success 200 {object} httpz.DataResponse[NoBodyPostResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/post [post]
func _SwagEdgeService_NoBodyPost0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*NoBodyPostResponse, error) {
		var in NoBodyPostRequest
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		out, err := srv.NoBodyPost(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary GetWithForm
// @Description GetWithForm binds fields as form data on a GET request.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param upload_name query string false "upload_name"
// @Param upload_size query integer false "upload_size"
// @Success 200 {object} httpz.DataResponse[GetWithFormResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/form [get]
func _SwagEdgeService_GetWithForm0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*GetWithFormResponse, error) {
		var in GetWithFormRequest
		if err := ctx.BindForm(&in); err != nil {
			return nil, err
		}
		out, err := srv.GetWithForm(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary WildcardList
// @Description WildcardList binds a repeated string to a catch-all path segment.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param names path string true "names"
// @Success 200 {object} httpz.DataResponse[WildcardListResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/repeated/{names} [get]
func _SwagEdgeService_WildcardList0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*WildcardListResponse, error) {
		var in WildcardListRequest
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.WildcardList(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary MapBody
// @Description MapBody projects the request body onto a map field.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param request body map[string]string true "request body"
// @Success 200 {object} httpz.DataResponse[MapBodyResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/map [post]
func _SwagEdgeService_MapBody0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*MapBodyResponse, error) {
		var in MapBodyRequest
		if err := ctx.BindJSON(&in.Attrs); err != nil {
			return nil, err
		}
		out, err := srv.MapBody(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary ScalarResponseBody
// @Description ScalarResponseBody projects the response onto a scalar string field.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param filter query string false "filter"
// @Success 200 {object} httpz.DataResponse[string]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/scalar-response [get]
func _SwagEdgeService_ScalarResponseBody0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (string, error) {
		var in ScalarResponseBodyRequest
		if err := ctx.BindQuery(&in); err != nil {
			return "", err
		}
		out, err := srv.ScalarResponseBody(ctx.Context(), &in)
		if err != nil {
			return "", err
		}
		return out.Token, nil
	})
}

// @Summary MapResponseBody
// @Description MapResponseBody projects the response onto a map field.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Success 200 {object} httpz.DataResponse[map[string]string]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/map-response [get]
func _SwagEdgeService_MapResponseBody0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (map[string]string, error) {
		var in MapResponseBodyRequest
		out, err := srv.MapResponseBody(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out.Labels, nil
	})
}

// @Summary ListResponseBody
// @Description ListResponseBody projects the response onto a repeated message field.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Success 200 {object} httpz.DataResponse[[]EdgeItem]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/list-response [get]
func _SwagEdgeService_ListResponseBody0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) ([]*EdgeItem, error) {
		var in ListResponseBodyRequest
		out, err := srv.ListResponseBody(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out.Items, nil
	})
}

// @Summary EnumQuery
// @Description EnumQuery binds an enum field as a query parameter.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param status query EdgeStatus false "status"
// @Success 200 {object} httpz.DataResponse[EnumQueryResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/enum [get]
func _SwagEdgeService_EnumQuery0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*EnumQueryResponse, error) {
		var in EnumQueryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		out, err := srv.EnumQuery(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary EnumListQuery
// @Description EnumListQuery binds a repeated enum as a query parameter. swag only, accepts primitive arrays in parameters, so the elements must render as, their underlying scalar.
// @Tags testdata.swag.v1,testdata.swag.v1.SwagEdgeService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param statuses query []integer false "statuses"
// @Success 200 {object} httpz.DataResponse[EnumQueryResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /api/swag/enum-list [get]
func _SwagEdgeService_EnumListQuery0_HTTP_Handler(srv SwagEdgeServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*EnumQueryResponse, error) {
		var in EnumListQueryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return nil, err
		}
		out, err := srv.EnumListQuery(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterSwagEdgeServiceHTTPServer(route httpx.Router, srv SwagEdgeServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("POST", "/api/swag/post", _SwagEdgeService_NoBodyPost0_HTTP_Handler(srv))
	r.Handle("GET", "/api/swag/form", _SwagEdgeService_GetWithForm0_HTTP_Handler(srv))
	r.Handle("GET", "/api/swag/repeated/*names", _SwagEdgeService_WildcardList0_HTTP_Handler(srv))
	r.Handle("POST", "/api/swag/map", _SwagEdgeService_MapBody0_HTTP_Handler(srv))
	r.Handle("GET", "/api/swag/scalar-response", _SwagEdgeService_ScalarResponseBody0_HTTP_Handler(srv))
	r.Handle("GET", "/api/swag/map-response", _SwagEdgeService_MapResponseBody0_HTTP_Handler(srv))
	r.Handle("GET", "/api/swag/list-response", _SwagEdgeService_ListResponseBody0_HTTP_Handler(srv))
	r.Handle("GET", "/api/swag/enum", _SwagEdgeService_EnumQuery0_HTTP_Handler(srv))
	r.Handle("GET", "/api/swag/enum-list", _SwagEdgeService_EnumListQuery0_HTTP_Handler(srv))
}
