// Code generated by protoc-gen-sphere. DO NOT EDIT.
// versions:
// - protoc             v5.29.0
// source: wildcard.proto

package wildcardv1

import (
	context "context"
	httpx "github.com/go-sphere/httpx"
	httpz "github.com/go-sphere/sphere/server/httpz"
)

var _ = new(context.Context)
var _ = new(httpx.Router)
var _ = new(httpz.ErrorResponse)

const OperationFileServiceArchive = "/testdata.wildcard.v1.FileService/Archive"
const OperationFileServiceDownload = "/testdata.wildcard.v1.FileService/Download"
const OperationFileServicePreview = "/testdata.wildcard.v1.FileService/Preview"

var EndpointsFileService = [...][3]string{
	{OperationFileServiceDownload, "GET", "/v1/files/*path"},
	{OperationFileServicePreview, "GET", "/v1/preview/:name"},
	{OperationFileServiceArchive, "GET", "/v1/archive/assets/*path"},
}

type FileServiceHTTPServer interface {
	// Archive Archive uses a literal prefix with a double wildcard:
	// /v1/archive/{path=assets/**} -> /v1/archive/assets/*path.
	Archive(context.Context, *ArchiveRequest) (*ArchiveResponse, error)
	// Download Download uses a bare double wildcard: /v1/files/{path=**} -> /v1/files/*path.
	Download(context.Context, *DownloadRequest) (*DownloadResponse, error)
	// Preview Preview uses a single wildcard: /v1/preview/{name=*} -> /v1/preview/:name.
	Preview(context.Context, *PreviewRequest) (*PreviewResponse, error)
}

// @Summary Download
// @Description Download uses a bare double wildcard: /v1/files/{path=**} -> /v1/files/*path.
// @Tags testdata.wildcard.v1,testdata.wildcard.v1.FileService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param path path string true "path"
// @Success 200 {object} httpz.DataResponse[DownloadResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /v1/files/{path} [get]
func _FileService_Download0_HTTP_Handler(srv FileServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*DownloadResponse, error) {
		var in DownloadRequest
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.Download(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary Preview
// @Description Preview uses a single wildcard: /v1/preview/{name=*} -> /v1/preview/:name.
// @Tags testdata.wildcard.v1,testdata.wildcard.v1.FileService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param name path string true "name"
// @Success 200 {object} httpz.DataResponse[PreviewResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /v1/preview/{name} [get]
func _FileService_Preview0_HTTP_Handler(srv FileServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*PreviewResponse, error) {
		var in PreviewRequest
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.Preview(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

// @Summary Archive
// @Description Archive uses a literal prefix with a double wildcard:, /v1/archive/{path=assets/**} -> /v1/archive/assets/*path.
// @Tags testdata.wildcard.v1,testdata.wildcard.v1.FileService
// @Accept json
// @Produce json
// @Param Authorization header string false "Bearer token"
// @Param path path string true "path"
// @Success 200 {object} httpz.DataResponse[ArchiveResponse]
// @Failure 400,401,403,500,default {object} httpz.ErrorResponse
// @Router /v1/archive/assets/{path} [get]
func _FileService_Archive0_HTTP_Handler(srv FileServiceHTTPServer) httpx.Handler {
	return httpz.WithJson(func(ctx httpx.Context) (*ArchiveResponse, error) {
		var in ArchiveRequest
		if err := ctx.BindURI(&in); err != nil {
			return nil, err
		}
		out, err := srv.Archive(ctx.Context(), &in)
		if err != nil {
			return nil, err
		}
		return out, nil
	})
}

func RegisterFileServiceHTTPServer(route httpx.Router, srv FileServiceHTTPServer) {
	r := route.Group("/")
	r.Handle("GET", "/v1/files/*path", _FileService_Download0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/preview/:name", _FileService_Preview0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/archive/assets/*path", _FileService_Archive0_HTTP_Handler(srv))
}
