package http

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

// formatProtocVersion formats a protoc compiler version as "vMAJOR.MINOR.PATCH[-SUFFIX]".
// A nil version renders as "(unknown)".
func formatProtocVersion(v *pluginpb.Version) string {
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// pluginName is the generator name recorded in generated file headers.
const pluginName = "protoc-gen-sphere"

// formatPluginVersion returns the plugin version recorded in the header, or
// "(unknown)" when none is configured (mirroring formatProtocVersion).
func formatPluginVersion(v string) string {
	if v == "" {
		return "(unknown)"
	}
	return v
}

// formatFileHeader builds the standard "Code generated ... DO NOT EDIT" header
// lines, including the package declaration. Following the protoc-gen-go
// convention, the versions block lists the plugin and then protoc, with the
// tool names padded to a common width. When deprecated is true the source line
// is replaced with a deprecation notice.
func formatFileHeader(pluginVersion, protocVersion, sourcePath, pkgName string, deprecated bool) []string {
	lines := []string{
		"// Code generated by " + pluginName + ". DO NOT EDIT.",
		"// versions:",
		fmt.Sprintf("// - %-*s %s", len(pluginName), pluginName, formatPluginVersion(pluginVersion)),
		fmt.Sprintf("// - %-*s %s", len(pluginName), "protoc", protocVersion),
	}
	if deprecated {
		lines = append(lines, fmt.Sprintf("// %s is a deprecated file.", sourcePath))
	} else {
		lines = append(lines, fmt.Sprintf("// source: %s", sourcePath))
	}
	lines = append(lines, "", fmt.Sprintf("package %s", pkgName), "")
	return lines
}

func generateFileHeader(plugin *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, pluginVersion string) {
	lines := formatFileHeader(
		pluginVersion,
		protocVersion(plugin),
		file.Desc.Path(),
		string(file.GoPackageName),
		file.Proto.GetOptions().GetDeprecated(),
	)
	for _, line := range lines {
		g.P(line)
	}
}

// formatMethodComment formats a method's leading proto comment into Go doc
// comment lines, prefixing the first line with the method name. Empty input
// yields an empty string.
func formatMethodComment(methodName, leading string) string {
	if leading == "" {
		return ""
	}
	cmp := strings.Split(strings.TrimSuffix(leading, "\n"), "\n")
	if len(cmp) == 0 {
		return ""
	}
	lines := []string{fmt.Sprintf("// %s %s", methodName, strings.TrimSpace(cmp[0]))}
	for _, line := range cmp[1:] {
		if strings.TrimSpace(line) == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("// %s", strings.TrimSpace(line)))
	}
	return strings.Join(lines, "\n")
}

// defaultHTTPPath builds the default HTTP path used when a method has no (or an
// empty) google.api.http rule: "<prefix>/<fullName>/<method>".
func defaultHTTPPath(prefix, fullName, method string) string {
	return fmt.Sprintf("%s/%s/%s", prefix, fullName, method)
}

// dotPrefixedPath joins a Go field key path with "." and adds a leading "." when
// the result is non-empty (so it can be appended directly to a receiver). An
// empty path yields an empty string.
func dotPrefixedPath(goKeys []string) string {
	joined := strings.Join(goKeys, ".")
	if joined == "" {
		return ""
	}
	return "." + joined
}
