package http

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/types/pluginpb"
)

// formatProtocVersion formats a protoc compiler version as "vMAJOR.MINOR.PATCH[-SUFFIX]".
// A nil version renders as "(unknown)".
func formatProtocVersion(v *pluginpb.Version) string {
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

// formatFileHeader builds the standard "Code generated ... DO NOT EDIT" header
// lines, including the package declaration. When deprecated is true the source
// line is replaced with a deprecation notice.
func formatFileHeader(version, sourcePath, pkgName string, deprecated bool) []string {
	lines := []string{
		"// Code generated by protoc-gen-sphere. DO NOT EDIT.",
		"// versions:",
		fmt.Sprintf("// - protoc             %s", version),
	}
	if deprecated {
		lines = append(lines, fmt.Sprintf("// %s is a deprecated file.", sourcePath))
	} else {
		lines = append(lines, fmt.Sprintf("// source: %s", sourcePath))
	}
	lines = append(lines, "", fmt.Sprintf("package %s", pkgName), "")
	return lines
}

// formatMethodComment formats a method's leading proto comment into Go doc
// comment lines, prefixing the first line with the method name. Empty input
// yields an empty string.
func formatMethodComment(methodName, leading string) string {
	if leading == "" {
		return ""
	}
	cmp := strings.Split(strings.TrimSuffix(leading, "\n"), "\n")
	if len(cmp) == 0 {
		return ""
	}
	lines := []string{fmt.Sprintf("// %s %s", methodName, strings.TrimSpace(cmp[0]))}
	for _, line := range cmp[1:] {
		if strings.TrimSpace(line) == "" {
			continue
		}
		lines = append(lines, fmt.Sprintf("// %s", strings.TrimSpace(line)))
	}
	return strings.Join(lines, "\n")
}

// defaultHTTPPath builds the default HTTP path used when a method has no (or an
// empty) google.api.http rule: "<prefix>/<fullName>/<method>".
func defaultHTTPPath(prefix, fullName, method string) string {
	return fmt.Sprintf("%s/%s/%s", prefix, fullName, method)
}

// dotPrefixedPath joins a Go field key path with "." and adds a leading "." when
// the result is non-empty (so it can be appended directly to a receiver). An
// empty path yields an empty string.
func dotPrefixedPath(goKeys []string) string {
	joined := strings.Join(goKeys, ".")
	if joined == "" {
		return ""
	}
	return "." + joined
}
