package http

import (
	"reflect"
	"testing"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func TestFormatProtocVersion(t *testing.T) {
	tests := []struct {
		name string
		v    *pluginpb.Version
		want string
	}{
		{"nil", nil, "(unknown)"},
		{"no suffix", &pluginpb.Version{Major: proto.Int32(5), Minor: proto.Int32(29), Patch: proto.Int32(0)}, "v5.29.0"},
		{"suffix", &pluginpb.Version{Major: proto.Int32(4), Minor: proto.Int32(25), Patch: proto.Int32(1), Suffix: proto.String("rc1")}, "v4.25.1-rc1"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := formatProtocVersion(tt.v); got != tt.want {
				t.Errorf("formatProtocVersion() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestFormatFileHeader(t *testing.T) {
	got := formatFileHeader("v5.29.0", "api/v1/foo.proto", "foov1", false)
	want := []string{
		"// Code generated by protoc-gen-sphere. DO NOT EDIT.",
		"// versions:",
		"// - protoc             v5.29.0",
		"// source: api/v1/foo.proto",
		"",
		"package foov1",
		"",
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("formatFileHeader() = %#v, want %#v", got, want)
	}

	dep := formatFileHeader("v5.29.0", "api/v1/foo.proto", "foov1", true)
	if dep[3] != "// api/v1/foo.proto is a deprecated file." {
		t.Errorf("deprecated header line = %q", dep[3])
	}
}

func TestFormatMethodComment(t *testing.T) {
	tests := []struct {
		name    string
		method  string
		leading string
		want    string
	}{
		{"empty", "RunTest", "", ""},
		{"single line", "RunTest", " does a thing\n", "// RunTest does a thing"},
		{"multi line", "RunTest", "line1\nline2\nline3\n", "// RunTest line1\n// line2\n// line3"},
		{"blank interior lines skipped", "RunTest", "line1\n\nline2\n", "// RunTest line1\n// line2"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := formatMethodComment(tt.method, tt.leading); got != tt.want {
				t.Errorf("formatMethodComment(%q, %q) = %q, want %q", tt.method, tt.leading, got, tt.want)
			}
		})
	}
}

func TestDefaultHTTPPath(t *testing.T) {
	if got := defaultHTTPPath("", "pkg.v1.Svc", "Method"); got != "/pkg.v1.Svc/Method" {
		t.Errorf("defaultHTTPPath empty prefix = %q", got)
	}
	if got := defaultHTTPPath("/prefix", "pkg.v1.Svc", "Method"); got != "/prefix/pkg.v1.Svc/Method" {
		t.Errorf("defaultHTTPPath with prefix = %q", got)
	}
}

func TestDotPrefixedPath(t *testing.T) {
	tests := []struct {
		name string
		in   []string
		want string
	}{
		{"nil", nil, ""},
		{"empty", []string{}, ""},
		{"single", []string{"Request"}, ".Request"},
		{"nested", []string{"Outer", "Inner"}, ".Outer.Inner"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := dotPrefixedPath(tt.in); got != tt.want {
				t.Errorf("dotPrefixedPath(%v) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}
